const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');let errors=[];
function launch(seed,broken=false){return new JSDOM(source,{url:'https://example.com/mabase/',runScripts:'dangerously',beforeParse(w){w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.confirm=()=>true;w.addEventListener('error',e=>errors.push(e.message));if(seed)w.localStorage.setItem('mabase-progress-v1',JSON.stringify(seed));if(broken)w.Storage.prototype.setItem=()=>{throw Error('denied')};}})}
(async()=>{const d=launch({'code-briques':true,'reform:code-briques':'Mes anciennes notes'}),w=d.window,doc=w.document;assert.ok(doc.querySelector('.grid'));const total=w.eval('lessons.length');let count=0;
for(const s of w.eval('SECTIONS')){w.eval(`section('${s.id}')`);assert.equal(doc.querySelectorAll('.lesson-card').length,s.lessons.length);for(const l of s.lessons){w.eval(`lesson('${s.id}','${l.id}')`);assert.equal(doc.querySelector('h1').textContent,l.title);for(const b of l.blocks){for(const line of (b.code||[]).flat())assert.ok(doc.querySelector('main').textContent.includes(line),'missing '+line)}count++}}
w.eval("lesson('code','code-briques')");assert.equal(doc.querySelector('textarea').value,'Mes anciennes notes');doc.querySelector('textarea').value='<script>alert(1)</script> & note';doc.querySelector('textarea').dispatchEvent(new w.Event('input'));assert.equal(JSON.parse(w.localStorage.getItem('mabase-progress-v1'))['reform:code-briques'],'<script>alert(1)</script> & note');doc.querySelector('#doneBtn').click();assert.equal(doc.querySelector('#doneBtn').getAttribute('aria-pressed'),'false');w.eval("search('reseau')");assert.ok(doc.querySelectorAll('#results .lesson-card').length>0);w.eval("search('zzznothing')");assert.equal(doc.querySelectorAll('#results .lesson-card').length,0);w.eval("lesson('bad','missing')");assert.equal(doc.querySelector('h1').textContent,'Leçon introuvable');
w.eval("lesson('code','code-briques')");w.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:'Retour de test <script>abc</script>'}}]})});doc.querySelector('#tutorBtn').click();await new Promise(r=>setTimeout(r,5));assert.ok(doc.querySelector('#tutorOut').textContent.includes('<script>'));assert.equal(doc.querySelectorAll('#tutorOut script').length,0);assert.equal(doc.querySelector('#tutorBtn').disabled,false);
w.fetch=async()=>{throw Error('network')};doc.querySelector('#tutorBtn').click();await new Promise(r=>setTimeout(r,5));assert.ok(doc.querySelector('#tutorOut').textContent.includes('Impossible'));assert.equal(doc.querySelector('#tutorBtn').disabled,false);
const reload=launch(JSON.parse(w.localStorage.getItem('mabase-progress-v1')));reload.window.eval("lesson('code','code-briques')");assert.equal(reload.window.document.querySelector('textarea').value,'<script>alert(1)</script> & note');
const bad=launch(null,true);assert.ok(bad.window.document.querySelector('h1'));bad.window.eval("lesson('code','code-briques')");assert.ok(bad.window.document.querySelector('#saveStatus').textContent.includes('indisponible'));assert.deepEqual(errors,[]);assert.equal(count,total);console.log(`PASS: ${count} lessons, all code lines, migrated notes, save/reload, progress, search, invalid routes, tutor success/failure, safe rendering, storage failure.`);[d,reload,bad].forEach(x=>x.window.close())})().catch(e=>{console.error(e);process.exit(1)});
